# Generated by Django 4.0.4 on 2022-05-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('note', models.TextField(default='', verbose_name='Примечание')),
                ('status', models.IntegerField(choices=0, default=0, verbose_name='Статус')),
                ('important', models.BooleanField(default=False, verbose_name='Важно')),
                ('public', models.BooleanField(default=False, verbose_name='Важно')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('deadline', models.DateTimeField(default=task.models._get_next_day, verbose_name='Выполнить до')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
